version: 2
registries:
  nexus:
    type: maven-repository
    url: https://labs.travsport.se/nexus/repository/maven-public
    username: dependabot
    password: ${{secrets.NEXUS_DEPENDABOT_PWD}}
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - nexus
    schedule:
      interval: "daily"
    allow:
      # Allow updates for Google but not it.unimi.dsi
      - dependency-name: "com.google*"
